version: '3'

services:
  app:
    build: .
    container_name: yandex_direct_conn
    ports:
      - "8030:15600"
    restart: always
    command: bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 15600"
    env_file:
      - .env
